version: '3.1'
services:
  stats-server:
    build: ewm-stats-service
    image: ewm-stats-service
    container_name: ewm-stats
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/eventwithme-stats
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-db-stats
    ports:
      - 6541:5432
    environment:
      - POSTGRES_DB=eventwithme-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-main-service
    image: ewm-main-service
    container_name: ewm-main
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/eventwithme
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - 6542:5432
    environment:
      - POSTGRES_DB=eventwithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
